CapaPresentacionAdmin/Controllers/MercaderiaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MercaderiaController : Controller
    {
        // GET: Mercaderia
        public ActionResult RegistrarEntrada()
        {
            return View();
        }
        public ActionResult ListadoEntrada()
        {
            return View();
        }
        public ActionResult RegistrarSalida()
        {
            return View();
        }
        public ActionResult ListadoSalidas()
        {
            return View();
        }
         
        public ActionResult Categoria()
        {
            return View();
        }
         public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }

        // =============CATEGORIA==============
        #region CATEGORIA
        public JsonResult ListarCategoria()
        {

            List<Categoria> oLista = new List<Categoria>();

            oLista = new CN_Categoria().Listar();

            //return Json(oLista, JsonRequestBehavior.AllowGet);
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables
        }


        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdCategoria == 0)//verifica si es un usuario nuevo pasado por objeto
            {
                resultado = new CN_Categoria().Registrar(objeto, out mensaje);//devuelve el Id del usuario
            }
            else
            {
                resultado = new CN_Categoria().Editar(objeto, out mensaje);// edita al usurio 
            }
            //devuelve un json con el resultado de los anteriores if llamado igual resultado
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables

        }



        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        //===============MARCA===============

        #region MARCA
        public JsonResult ListarMarca()
        {

            List<Marca> oLista = new List<Marca>();

            oLista = new CN_Marca().Listar();

            //return Json(oLista, JsonRequestBehavior.AllowGet);
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables
        }


        [HttpPost]
        public JsonResult GuardarMarca(Marca objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdMarca == 0)//verifica si es un usuario nuevo pasado por objeto
            {
                resultado = new CN_Marca().Registrar(objeto, out mensaje);//devuelve el Id del usuario
            }
            else
            {
                resultado = new CN_Marca().Editar(objeto, out mensaje);// edita al usurio 
            }
            //devuelve un json con el resultado de los anteriores if llamado igual resultado
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables

        }



        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        //===============PRODUCTO===============
        #region PRODUCTO
        public JsonResult ListarProducto()
        {

            List<Producto> oLista = new List<Producto>();

            oLista = new CN_Producto().Listar();

            //return Json(oLista, JsonRequestBehavior.AllowGet);
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);//cambiamos la vista para dataTables
        }



        [HttpPost]
        public JsonResult GuardarProducto(string objeto, HttpPostedFileBase archivoImagen)
        {
            //object resultado;
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool guardar_imagen_exito = true; 

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);
            decimal precio;
            //estrae el precio de la BD y lo Transforma al formato de la region 
            if (decimal.TryParse(oProducto.PrecioTexto, NumberStyles.AllowDecimalPoint,new CultureInfo("es-PE"),out precio))
            {
                oProducto.Precio = precio;
            }
            else
            {
                   //en caso de fallar la transformacion devuelve un mensaje
                return Json(new { operacionExitosa = false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }


            if (oProducto.IdProducto == 0)//verifica si es un producto es distinto de vacio
            {
                int idProductoGenerado = new CN_Producto().Registrar(oProducto, out mensaje);//devuelve el Id del producto
                if (idProductoGenerado!=0) //captura el id de producto
                {
                    oProducto.IdProducto = idProductoGenerado;
                }
                else
                {
                    operacion_exitosa = false;
                }
            }
            else
            {
                operacion_exitosa = new CN_Producto().Editar(oProducto, out mensaje);// edita al producto 
            }



            if (operacion_exitosa)
            {
                if (archivoImagen != null)
                {
                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];//extrae de Configuracion el campo para guardar las imagnes en app dentro de web.config
                    string extension = Path.GetExtension(archivoImagen.FileName);//para obtener las extenciones
                    string nombre_imagen = string.Concat(oProducto.IdProducto.ToString(), extension);//para extraer el nombre de la imagen
                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));//almacena la imagen en la ruta
                    }catch(Exception ex)
                    {
                        string msg = ex.Message;
                        guardar_imagen_exito = false;
                    }

                    if (guardar_imagen_exito)//si se guarda la imagen almacena los datos en la BD
                    {
                        oProducto.RutaImagen = ruta_guardar;
                        oProducto.NombreImagen = nombre_imagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }
                    else
                    {
                        mensaje = "Se guardo el producto pero hubo problemas con la imagen";
                    }
                }
            }


            //devuelve un json con el resultado de los anteriores if llamado igual resultado
            return Json(new { operacionExitosa = operacion_exitosa, idGenerado=oProducto.IdProducto, mensaje = mensaje}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ImagenProducto(int id)
        {
            bool conversion;
            Producto oproducto = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();//extrae una consulta
            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oproducto.RutaImagen, oproducto.NombreImagen),out conversion);


            return Json(new
            {
                conversion = conversion,
                textoBase64=textoBase64,
                extension=Path.GetExtension(oproducto.NombreImagen)
            },
            JsonRequestBehavior.AllowGet
            );
        }


        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema inventario WEB</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">ADMINISTRADOR</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Ajustes</a></li>
                    <li><a class="dropdown-item" href="#!">Correo Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("CerrarSesion","Acceso")">Cerrar sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Panel Principal
                        </a><a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-alt"></i></div>
                            Usuarios
                        </a>
                        <a class="nav-link" href="@Url.Action("Categoria","Mercaderia")">
                            <div class="sb-nav-link-icon"><i class="fas fa-toolbox"></i></div>
                            Categorias
                        </a>
                        <div class="sb-sidenav-menu-heading">Productos</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-barcode"></i></div>
                            Entradas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("RegistrarEntrada","Mercaderia")">Registrar Entradas</a>
                                <a class="nav-link" href="@Url.Action("ListadoEntrada","Mercaderia")">Listado Entrada</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-cart-arrow-down"></i></div>
                            Salidas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Registrar Salida
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Articulos</a>
                                        <a class="nav-link" href="register.html">Insumos</a>
                                        <a class="nav-link" href="password.html">Papeleria</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Listado Salidas
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">Historico</a>
                                        <a class="nav-link" href="404.html">Semanal</a>
                                        <a class="nav-link" href="500.html">Diario</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Usuarios</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-check"></i></div>
                            Clientes
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                            Proveedores
                        </a>
                        <div class="sb-sidenav-menu-heading">Dashboard</div>
                        <a class="nav-link" href="@Url.Action("Marca","Mercaderia")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mercaderia")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Usted a iniciado como:</div>
                    Administrador
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Website 2022</div>
                        <div>
                            <a href="#">Politica de privacidad</a>
                            &middot;
                            <a href="#">Terminos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>